spring.application.name=Employee_Sort_data
# MySQL Database Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/poc?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false
#spring.datasource.username=root
#spring.datasource.password=root

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update 
 # Options: none, update, create, create-drop
spring.jpa.show-sql=true  
# Show SQL queries in the console (optional)
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Enable Hibernate to automatically create/drop tables
# spring.jpa.hibernate.ddl-auto=create-drop 
 # This will drop and create tables every time the app starts

# Enable H2 Console
spring.h2.console.enabled=true
# The path to access H2 console (default is /h2-console)
spring.h2.console.path=/h2-console
# JDBC URL of the H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.properties.hibernate.ejb.naming_strategy=org.hibernate.cfg.ImprovedNamingStrategy
#//
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.settings.trace=true
spring.h2.console.settings.web-allow-others=false
logging.level.org.hibernate.SQL=DEBUG